DROP TABLE IF EXISTS SCHEDULE;

CREATE TABLE SCHEDULE
(
ID int PRIMARY KEY AUTO_INCREMENT,
STUDENTS_FK int,
SPAN int NOT NULL,
CONSTRAINT FK_STUDENTS FOREIGN KEY (STUDENTS_FK) REFERENCES STUDENTS(ID)
);