DROP TABLE IF EXISTS STUDENTS;

CREATE TABLE STUDENTS
(
ID int PRIMARY KEY AUTO_INCREMENT,
FIRSTNAME varchar(255) NOT NULL,
LASTNAME varchar(255) NOT NULL,
PHONENUMBER varchar(10),
EMAIL varchar(255)
);